if(DEFINED CONFIGURATION_OUTPUT_DIRECTORY)
	set(CMAKE_RUNTIME_OUTPUT_DIRECTORY "${CONFIGURATION_OUTPUT_DIRECTORY}")
	set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY "${CONFIGURATION_OUTPUT_DIRECTORY}")
	set(CMAKE_LIBRARY_OUTPUT_DIRECTORY "${CONFIGURATION_OUTPUT_DIRECTORY}")
	set(CMAKE_PDB_OUTPUT_DIRECTORY     "${CONFIGURATION_OUTPUT_DIRECTORY}")

	if (CONFIGURATION_OUTPUT_DIRECTORY MATCHES "[dD]ebug$|[rR]elease$")
		set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_RELEASE "${CONFIGURATION_OUTPUT_DIRECTORY}")
		set(CMAKE_RUNTIME_OUTPUT_DIRECTORY_DEBUG   "${CONFIGURATION_OUTPUT_DIRECTORY}")

		set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_RELEASE "${CONFIGURATION_OUTPUT_DIRECTORY}")
		set(CMAKE_ARCHIVE_OUTPUT_DIRECTORY_DEBUG   "${CONFIGURATION_OUTPUT_DIRECTORY}")

		set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_RELEASE "${CONFIGURATION_OUTPUT_DIRECTORY}")
		set(CMAKE_LIBRARY_OUTPUT_DIRECTORY_DEBUG   "${CONFIGURATION_OUTPUT_DIRECTORY}")

		set(CMAKE_PDB_OUTPUT_DIRECTORY_RELEASE     "${CONFIGURATION_OUTPUT_DIRECTORY}")
		set(CMAKE_PDB_OUTPUT_DIRECTORY_DEBUG       "${CONFIGURATION_OUTPUT_DIRECTORY}")
	endif()
endif()

if(${CMAKE_SYSTEM_NAME} STREQUAL Linux)
	set(CMAKE_INSTALL_RPATH "$ORIGIN/../lib:$ORIGIN/lib:$ORIGIN/")
	set(CMAKE_BUILD_WITH_INSTALL_RPATH TRUE)
	set(CMAKE_SKIP_BUILD_RPATH FALSE)
	set(CMAKE_INSTALL_RPATH_USE_LINK_PATH TRUE)
endif()
